let i='atul kumar singh';
var profession='web developer/trainer';
console.log(i.length);
console.log(i.substring(2,4));
console.log(i.split(''));
console.log(i.split(' '));
console.log(i.toLowerCase());
console.log(i.toUpperCase());
console.log(`Hi! My name is ${i} and my profession is ${profession}`);
let num=[1,2,3,4,5];
console.log(num);
let numbers=[];
numbers.push(67);
numbers.unshift(90);
console.log(numbers);
numbers.push(89);
numbers.push(79);
numbers.pop();
console.log(numbers);
numbers.splice(0,1);
console.log(numbers);
let num2=numbers.includes(67);
console.log(num2);
console.log(numbers.indexOf(67));
